export const MESSAGE_TYPE_DEFAULT = 0;
export const MESSAGE_TYPE_SUMMARY = 2;
export const MESSAGE_TYPE_MISTAKEN_SUMMARY = 22;

export const SENDER_GPT = "-2";
export const SENDER_ADMIN = "-1"

export const SESSION_STATUS_NULL = 0
export const SESSION_STATUS_AI_RESPONDED = 1
export const SESSION_STATUS_ADMIN_RESPONDED = 5

export const SESSION_STATUS_USER_RESPONDED = 3
export const SESSION_STATUS_WANNA_CLOSE_SESSION = 4
export const SESSION_STATUS_SESSION_SUMMARIZED = 2
export const SESSION_STATUS_SESSION_MISTAKENLY_SUMMARIZED = 22