var confs = require('./Configs/confs.json');

module.exports = {
  API_KEY: confs.API_KEY,
  GOOGLE_YOUTUBE_KEY: confs.GOOGLE_YOUTUBE_KEY,
  MAILCHIMP_API_KEY: confs.MAILCHIMP_API_KEY,
  MAILCHIMP_API_SERVER_PREFIX: confs.MAILCHIMP_API_SERVER_PREFIX,
  SHA_SECRET: confs.SHA_SECRET,

  MY_MAIL: confs.MY_MAIL,
  MAILER_EMAIL: confs.MAILER_EMAIL,
  MAILER_PASS: confs.MAILER_PASS,

  MAILTRAP_KEY: confs.MAILTRAP_KEY,

  BREVO_KEY: confs.BREVO_KEY,

  GA_DATA_FLOW_ID: confs.GA_DATA_FLOW_ID,

  ELASTIC_MAIL_API_KEY: confs.ELASTIC_MAIL_API_KEY,
}
